# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        dindimg: ["docker:18.09-dind","docker:19.03-dind","docker:20.10-dind"]
        path: ["dockerfiles/01","dockerfiles/pytorchnocuda","dockerfiles/pytorchcuda"]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: build
        run: |
          echo "start image build benchmark..."
          echo "matrix.path ${{ matrix.path }}"
          echo "matrix.dindimg ${{ matrix.dindimg }}"

          ./build.sh ${{ matrix.path }} out.csv 2 ${{ matrix.dindimg }}
          echo "benchmark end."
          cat out.csv
              
